<?php

namespace App\Repositories;

use Doctrine\ORM\EntityRepository;
use Illuminate\Pagination\Paginator;
use Doctrine\Common\Collections\Criteria;
use LaravelDoctrine\ORM\Pagination\PaginatesFromParams;
use Illuminate\Contracts\Pagination\LengthAwarePaginator;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends EntityRepository
{
    use PaginatesFromParams;

    public const LIMIT = 15;

    /**
     * @param string $order
     * @param int    $limit
     * @param int    $page
     *
     * @return \Illuminate\Contracts\Pagination\LengthAwarePaginator|\Illuminate\Pagination\LengthAwarePaginator
     */
    public function all($order = Criteria::DESC, int $limit = self::LIMIT, int $page = 1) : LengthAwarePaginator
    {
        $query = $this->createQueryBuilder('c')
            ->orderBy('c.id', $order)
            ->getQuery();

        return $this->paginate($query, $limit, $page);
    }
}
